### ISSUE TITLE
Create pubspec.yaml for flutter_whisper_kit_android package

### ISSUE THREAD

**Issue by r0227n** [r0227n/flutter_whisper_kit#124]
## Summary
Create and configure pubspec.yaml for flutter_whisper_kit_android package with proper dependencies and platform configuration.

## Test-First Approach (Red-Green-Refactor)
**Red (5 min)**: Write test that validates pubspec.yaml structure and dependencies
**Green (15 min)**: Create pubspec.yaml with required configuration
**Refactor (10 min)**: Optimize dependencies and add missing metadata

## Success Criteria
- [ ] File `packages/flutter_whisper_kit_android/pubspec.yaml` exists
- [ ] Package name is correctly set to `flutter_whisper_kit_android`
- [ ] Version is set to `0.1.0`
- [ ] Flutter SDK dependency is properly configured
- [ ] flutter_whisper_kit dependency is correctly referenced
- [ ] Android platform configuration is present
- [ ] Plugin class is set to `FlutterWhisperKitAndroidPlugin`
- [ ] Package identifier is `com.r0227n.flutter_whisper_kit_android`

## Technical Requirements
- Follow pubspec.yaml structure from flutter_whisper_kit_apple
- Include proper flutter plugin configuration
- Set up platform-specific settings for Android
- Include dev_dependencies for testing

## Security Considerations
- No sensitive information in pubspec.yaml
- Proper version constraints for dependencies
- Secure package identifier naming convention

## Dependencies to Include
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_whisper_kit:
    path: ../flutter_whisper_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
```

## Platform Configuration
```yaml
flutter:
  plugin:
    platforms:
      android:
        package: com.r0227n.flutter_whisper_kit_android
        pluginClass: FlutterWhisperKitAndroidPlugin
```

## Files to Create/Modify
- `packages/flutter_whisper_kit_android/pubspec.yaml`

## Time Estimate: 30 minutes
